########################################################################################################
#
#                               Voyzu Framework
#                               Generic CloudFormation stack
#                               for SQS Queue and Lambda and trigger
#                               version 0.8
#
########################################################################################################

AWSTemplateFormatVersion: "2010-09-09"
# Set dynamically at deploy time.  The description as per package.json
Description: "[Description]"

########################################################################################################
#
#                                            Mappings (Constants)
#
########################################################################################################

# Mapping values are set dynamically at deploy time
Mappings:
  StackMappings:
    ComponentName:
      Value: [ComponentName] # Component name as per package.json
    ComponentType:
      Value: [ComponentType] # Voyzu Framework Component type as per package.json
    LambdaMemory:
      Value: [LambdaMemory] # Lambda Memory size (RAM) in Mb
    LambdaTimeout:
      Value: [LambdaTimeout] # Lambda function timeout in seconds
    S3Bucket:
      Value: [S3Bucket] # The AWS S3 Bucket where component build artifacts reside
    S3Key:
      Value: [S3Key] # The S3 key (file name) of the zipped lambda function
    S3TemplateUrl:
      Value: [S3TemplateUrl] # The AWS S3 URL this stack was installed from

Resources:

  ########################################################################################################
  #
  #                                            SSM Parameter
  #
  ########################################################################################################

  SsmParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name:  !Join [".", [!Ref AWS::StackName,"stack"]]
      Description: Component deployment version tracking
      Tier: Standard
      Type: String
      Value:  !FindInMap [StackMappings, S3TemplateUrl, Value]

      
  ########################################################################################################
  #
  #                                SQS
  #
  ########################################################################################################

  SqsQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Join ["",[!FindInMap [StackMappings, ComponentName, Value], ".fifo"]]
      FifoQueue: true
      FifoThroughputLimit: perMessageGroupId
      DeduplicationScope: messageGroup
      VisibilityTimeout: 400
      RedrivePolicy: 
        deadLetterTargetArn: 
          !Join ["", ["arn:aws:sqs:", !Ref "AWS::Region",":",!Ref "AWS::AccountId",":", "crm-sync-dead-letter.fifo"] ]
        maxReceiveCount: 1

  ########################################################################################################
  #
  #                                Lambda SQS Trigger from SQS Queue
  #
  ########################################################################################################
  
  LambdaSqsTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      Enabled: true
      FunctionName: crm-workflow-contact-change
      EventSourceArn:
         !GetAtt SqsQueue.Arn

########################################################################################################
#
#                                Outputs
#
########################################################################################################

Outputs:

  S3TemplateUrl:
    Value:
      !FindInMap [StackMappings, S3TemplateUrl, Value]